#!/usr/bin/env node

/**
 * Module dependencies.
 */

var appService = require('./api-cods-ruoyi')
// var debug = require('debug')('gfui:server')
var http = require('http')

/**
 * Get port from environment and store in Express.
 */
var port = normalizePort('28006')
var app = appService.app
app.set('port', port)
app.set('dist_path', '../dist_ruoyi')
appService.init()
/**
 * Event listener for HTTP server "error" event.
 */

function onError(error) {
  console.log('Systen Error:', error)
  if (error.syscall !== 'listen') {
    throw error
  }

  var bind = typeof port === 'string'
    ? 'Pipe ' + port
    : 'Port ' + port

  // handle specific listen errors with friendly messages
  switch (error.code) {
    case 'EACCES':
      console.error(bind + ' requires elevated privileges')
      process.exit(1)
      break
    case 'EADDRINUSE':
      console.error(bind + ' is already in use')
      process.exit(1)
      break
    default:
      throw error
  }
}

/**
 * Event listener for HTTP server "listening" event.
 */

function onListening() {
  var addr = server.address()
  var bind = typeof addr === 'string'
    ? 'pipe ' + addr
    : 'port ' + addr.port
  console.log('Listening on ' + bind)
}
/**
 * Create HTTP server.
 */
var server = http.createServer(app)
/**
 * Listen on provided port, on all network interfaces.
 */

server.listen(port)
server.on('error', onError)
server.on('listening', onListening)
process.on('uncaughtException', function(e) {
  console.log('UncaughtException:', e)
})
process.on('unhandledRejection', function(e, promise) {
  console.log('UnhandledRejection:', e)
})

/**
 * Normalize a port into a number, string, or false.
 */

function normalizePort(val) {
  var port = parseInt(val, 10)

  if (isNaN(port)) {
    // named pipe
    return val
  }

  if (port >= 0) {
    // port number
    return port
  }

  return false
}

