name: API Test

on:
  push:
    branches:
      - hai_dev
      - master
      - main
#测试
jobs:
  api-test:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests pyyaml allure-pytest

      - name: 执行接口自动化测试
        run: |
          pytest tests/test_login.py -v --alluredir=tests/allure-results