name: Auto Deploy

on:
  push:
    branches:
      - master
      - hai_dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /opt/Ruoyi-Vue
            ./deploy.sh